### ISSUE TITLE
[FIX] il y a un soucis avec les imports

### ISSUE THREAD

**Issue by j314h** [nsevendev/hecate#28]
## l'ide met toujours src devant dans les import au lieu de ../..

**Comment by Aurelien0192** [comment]
J'ai trouvé où le problème se situait, c'est la propriété baseUrl dans tsconfig qui formatait la path de l'import, en le supprimant, les imports sont corrects

**Comment by j314h** [comment]
> J'ai trouvé où le problème se situait, c'est la propriété baseUrl dans tsconfig qui formatait la path de l'import, en le supprimant, les imports sont corrects

et du coup t'as tester d'importer via l'ide ? voir si il résoud bien les paths ?
