### ISSUE TITLE
creation MCD

### ISSUE THREAD

**Issue by j314h** [nsevendev/hecate#9]
mettre en place schema drawio pour la database

**Comment by j314h** [comment]
@Aurelien0192 il faudra qu'on ce fasse un call

**Comment by Aurelien0192** [comment]
Okay pas de soucis, ça te vas si le call est ce soir?

**Comment by j314h** [comment]
@Aurelien0192 tu pourras regarder et voir si tout est OK pour toi ou si tu veux rajouter des choses dis mon en commentaire, sinon creer une MR de la branch MCD sur main et je la validerai.

pour info pour acceder à la doc via drawio, il faut utiliser le site pas l'application, quand tu es sur le site connecte toi avec github, ensuite fait ouvrir projet ou un truc comme ça et ensuite cherche notre projet et la branch MCD et il y a le fichier MCD tu l'ouvres et tu pourra apporter des modifications ou pas ... ;-)

**Comment by Aurelien0192** [comment]
@j314h c'est bon j'arrive bien à accéder au MCD via drawio. Je suis ok avec la quasi totalité, je ne vois juste pas à quoi correspond cg 😅

**Comment by j314h** [comment]
> @j314h c'est bon j'arrive bien à accéder au MCD via drawio. Je suis ok avec la quasi totalité, je ne vois juste pas à quoi correspond cg 😅

c'est pour les condition general ;-)
